# Generated by Django 3.2 on 2023-09-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_id',
            name='investment_plan_name',
            field=models.CharField(blank=True, default='MISSED-INFO', max_length=20, null=True),
        ),
    ]
